"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { getHistory, Decision } from "@/lib/api";

const ACTION_STYLES: Record<string, { text: string; bg: string; border: string }> = {
  BUY:  { text: "text-emerald-300", bg: "bg-emerald-950/40",  border: "border-emerald-700/40" },
  HOLD: { text: "text-amber-300",   bg: "bg-amber-950/40",    border: "border-amber-700/40"  },
  SELL: { text: "text-red-300",     bg: "bg-red-950/40",      border: "border-red-700/40"    },
};

export default function HistoryPage() {
  const [decisions, setDecisions] = useState<Decision[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getHistory().then((d) => { setDecisions(d); setLoading(false); });
  }, []);

  return (
    <div className="max-w-4xl mx-auto w-full px-4 py-8 space-y-6">

      {/* Header */}
      <div className="flex items-end justify-between border-b border-border/30 pb-4">
        <div>
          <h2 className="text-lg font-bold tracking-tight">Decision History</h2>
          <p className="text-xs text-muted-foreground/60 mt-0.5">
            All investment recommendations generated by the system
          </p>
        </div>
        {!loading && decisions.length > 0 && (
          <span className="label-xs">{decisions.length} record{decisions.length !== 1 ? "s" : ""}</span>
        )}
      </div>

      {loading && (
        <div className="flex items-center gap-3 text-sm text-muted-foreground">
          <span className="w-3 h-3 border-2 border-muted-foreground/30 border-t-muted-foreground rounded-full animate-spin" />
          Loading records…
        </div>
      )}

      {!loading && decisions.length === 0 && (
        <div className="rounded-xl border border-border/30 bg-card/30 p-12 text-center space-y-3">
          <div className="text-3xl opacity-20">📋</div>
          <p className="text-sm text-muted-foreground">No decisions recorded yet.</p>
          <Link href="/" className="inline-block text-xs text-primary/70 hover:text-primary underline transition-colors">
            Run your first analysis →
          </Link>
        </div>
      )}

      {!loading && decisions.length > 0 && (
        <div className="rounded-xl border border-border/30 overflow-hidden bg-card/20">

          {/* Table header */}
          <div className="grid grid-cols-[120px_80px_90px_80px_1fr_100px] gap-0 px-4 py-2.5 border-b border-border/30 bg-muted/10">
            {["Ticker", "Action", "Confidence", "Debate", "Explanation", "Date"].map((h) => (
              <span key={h} className="label-xs">{h}</span>
            ))}
          </div>

          {/* Rows */}
          <div className="divide-y divide-border/15">
            {decisions.map((d, i) => {
              const style = ACTION_STYLES[d.action] ?? { text: "text-muted-foreground", bg: "bg-transparent", border: "border-transparent" };
              const pct = Math.round((d.confidence ?? 0) * 100);

              return (
                <div
                  key={i}
                  className="grid grid-cols-[120px_80px_90px_80px_1fr_100px] gap-0 px-4 py-3 hover:bg-muted/8 transition-colors items-center group"
                >
                  {/* Ticker */}
                  <Link
                    href={`/analyze/${d.ticker}`}
                    className="font-mono font-bold text-sm text-foreground/90 hover:text-foreground group-hover:underline underline-offset-2 truncate"
                  >
                    {d.ticker}
                  </Link>

                  {/* Action badge */}
                  <div>
                    <span className={`inline-flex px-2 py-0.5 text-[10px] font-bold tracking-widest rounded border ${style.text} ${style.bg} ${style.border}`}>
                      {d.action}
                    </span>
                  </div>

                  {/* Confidence bar + pct */}
                  <div className="pr-4">
                    <div className="flex items-center gap-2">
                      <div className="flex-1 h-1 bg-muted/40 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${
                            d.action === "BUY" ? "bg-emerald-500" :
                            d.action === "SELL" ? "bg-red-500" : "bg-amber-500"
                          }`}
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                      <span className="text-[10px] font-mono text-muted-foreground/70 shrink-0">{pct}%</span>
                    </div>
                  </div>

                  {/* Debate winner */}
                  <span className="text-xs text-muted-foreground/60 capitalize font-mono">{d.debate_winner ?? "—"}</span>

                  {/* Explanation */}
                  <span className="text-xs text-muted-foreground/55 truncate pr-4">{d.explanation ?? "—"}</span>

                  {/* Date */}
                  <span className="text-[10px] font-mono text-muted-foreground/40">{d.created_at?.slice(0, 10) ?? "—"}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
